version: 2.1

orbs:
  continuation: circleci/continuation@0.2.0

setup: true

jobs:
  build:
    docker:
      - image: circleci/node:8.11
    resource_class: small
    working_directory: ~/repo
    steps:
      - checkout
      - continuation/finish:
          circleci_domain: custeng-server-4.eks-dev.sphereci.com

workflows:
  setup:
    jobs:
      - build
