version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:8.11
    resource_class: small
    working_directory: ~/repo
    steps:
      - checkout

workflows:
  main:
    jobs:
      - build
